### ISSUE TITLE
上帝套问题

### ISSUE THREAD

**Issue by 623667595** [KELETU66666/Thaumisc#30]
穿上帝套过一段时间F5视角 严重掉帧 背包内也掉帧 切换回去帧数恢复  不知道和光影有没有关系
已测试是上帝法袍的问题

**Comment by KELETU66666** [comment]
暂未发现此种情况...

感谢反馈~

**Comment by 623667595** [comment]
能不能加个配置控制上帝套翅膀 我感觉 就是那玩儿卡的

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/175532655-9eba8eb0-730c-49bc-b6ef-221ae7c34c8d.png)

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/175532708-58738118-a566-45e1-9d66-9120534bea23.png)

**Comment by 623667595** [comment]
而且穿戴发生卡顿以后，就算脱掉也不会流畅起来了，只能脱掉，重启客户端

**Comment by KELETU66666** [comment]
emmmm，好的，我这边会处理一下

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/175799268-4418143b-0041-4383-93eb-b58464d4b46b.png)

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/175799321-b4724e2a-2bb0-4054-9866-4160c8e33ca0.png)

**Comment by 623667595** [comment]
按F5就卡的一批 是不是翅膀的锅？ 原版都这样

**Comment by 623667595** [comment]
人物模型卡了 打开背包也卡顿了 卡的一批 优化太差了

**Comment by 623667595** [comment]
> emmmm，好的，我这边会处理一下 顺带一提，您可以试试关掉光影看看效果，如果还不行的话，请及时告诉我，谢谢

emmmmmm 兄弟弄个客户端版本解决解决

**Comment by KELETU66666** [comment]
您如果确定是这个模组的问题的话，我会考虑的...

**Comment by 623667595** [comment]
就是穿这个胸甲才卡的呀 不穿这上帝胸甲屁事没有的

**Comment by 623667595** [comment]
其他MOD 所有装备都没这种情况

**Comment by KELETU66666** [comment]
已经收到，正在考虑修复
