### ISSUE TITLE
更新之后出现bug

### ISSUE THREAD

**Issue by 623667595** [KELETU66666/Thaumisc#50]
![image](https://user-images.githubusercontent.com/88877796/184404113-515107e7-5e71-4ec4-a0c8-85d386e3b280.png)
地形渲染出现问题  上帝稿左键 基岩直接变成传送门

**Comment by KELETU66666** [comment]
渲染可能是您的内存设置问题...
至于基岩...
基岩在y<2的坐标下才会变成传送门。
