### ISSUE TITLE
Eliminating All Warp Causes Crash?

### ISSUE THREAD

**Issue by Handeril** [KELETU66666/Thaumisc#55]
The Cleansing Pendant is an amazing thing, however, if you try to completely clear all your warp, you'll either gain warp, or crash the game when all warp is cleared.

Here's the logs:
[crash-2022-09-18_00.05.04-server.txt](https://github.com/KELETU66666/Thaumisc/files/9593236/crash-2022-09-18_00.05.04-server.txt)

[latest.log](https://github.com/KELETU66666/Thaumisc/files/9593237/latest.log)

**Comment by KELETU66666** [comment]
Received, checking the report now, thanks for your feedback

**Comment by KELETU66666** [comment]
fixed
